---
abstract: 'a fake HTTP server'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  LWP::UserAgent: 0
  Test::Exception: 0
  Test::More: 0.98
  Test::TCP: 0
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Fake-HTTPD
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  HTTP::Daemon::SSL: 0
requires:
  Carp: 0
  Exporter: 0
  HTTP::Daemon: 0
  HTTP::Message::PSGI: 0
  Scalar::Util: 1.14
  Test::TCP: 0
  Time::HiRes: 0
  URI: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/masaki/Test-Fake-HTTPD.git
version: 0.04
